### ISSUE TITLE
Incorporate MOSFET dead time into SPDM generation

### ISSUE THREAD

**Issue by SM-dot** [UCI-HyperXite/inverter-control#11]
Deadtime - adding a delay when going from low to high(time TBD) to avoid short circuiting. 

Basically, we can check if previously it was low and the current state is high then we can delay for X nanoseconds. In case of high to low, no time delay is needed as it is safe(as discussed with professor Smedley).

**Comment by taesungh** [comment]
For reference, the two outputs for each phase should never both be high at the same time:
![Visualization of dead time showing pauses where both outputs are momentarily low during switching](https://github.com/UCI-HyperXite/inverter-control/assets/44419552/354e4253-f0ca-41ab-87ea-cf581a3b5e6c)

**Comment by SM-dot** [comment]
Hi, for this - this is what I have so far:
if (prev_state == 0 && Vu == 1)
{
        sleep_us(5); //time TBD 
        prev_state += 1;
}

basically keeping track of the states as recommended by Chris. Do you have any other suggestions/ plans of implementation?

**Comment by taesungh** [comment]
From discussion in lab, the gate driver has a rising time and propagation delay that is longer than the falling time and propagation delay, so we shouldn't need to worry about implementing dead time on the software side.
