### ISSUE TITLE
(Three Phase) Variable Frequency and Amplitude

### ISSUE THREAD

**Issue by samderanova** [UCI-HyperXite/inverter-control#12]
To operate the LIM at optimal efficiency, we'll need to be able to support variable frequency and amplitude. We'll need to update the `run_one_inverter` function (or a parent wrapper) to accept frequency and amplitude as parameters and then scale the PDM wave accordingly.

**Comment by taesungh** [comment]
Let's make this a priority again to unblock #24. Should be as simple as rescaling the sine wave being sampled by multiplying the desired relative amplitude.
