### ISSUE TITLE
Inverter code fails when ran without serial monitor

### ISSUE THREAD

**Issue by ACEslava** [UCI-HyperXite/inverter-control#42]
Line 115 runs before Line 116 and presumably errors when serial monitor isn't connected.

https://github.com/UCI-HyperXite/inverter-control/blob/011752f66bfc0e4796b7e04adcc9b436e8f5b0f1/src/main.cpp#L102-L119

**Comment by pikap0ng** [comment]
Changed code structure to wait for the USB device to connect before launching monitor_serial() on second core. 
Added max attempts timeout handler to skip serial monitor if not connected to avoid infinite wait time.

**Comment by taesungh** [comment]
This is the intended behavior for final usage together with the main pod operation program. If you want to run the program separately for testing independently, I would recommend having a separate version that gets compiled based on the build type or creating multiple executables with different `main` functions as entry points.
