### ISSUE TITLE
Optimize three-phase SPDM generation

### ISSUE THREAD

**Issue by samderanova** [UCI-HyperXite/inverter-control#9]
Currently, the SPDM runs at 18 kHz, which is not enough for 20 kHz (outside the range of human hearing). To optimize this, we were originally considering using a Taylor series approximation of `sin`, which although allowed us to run well above 20 kHz (slightly greater than 60 kHz), the resulting waveform was not as good as it could be. Thus, we decided on a different optimization using the [`sin` addition rule](https://mathworld.wolfram.com/TrigonometricAdditionFormulas.html). This issue is devoted to implementing said optimization.

**Comment by taesungh** [comment]
Reopening to explore using `float` instead of `double` as mentioned in #10.
